apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default 
  name: faas-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: secret-pod-reader
rules:
 - apiGroups: ["metrics.k8s.io"]
   resources: ["pods"]
   verbs: ["get", "watch", "list"]
 - apiGroups: [""] # "" indicates the core API group
   resources: ["secrets"]
   verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: faas-clusterbinding
subjects:
- kind: ServiceAccount
  name: faas-monitor
  namespace: default 
roleRef:
  kind: ClusterRole
  name: secret-pod-reader
  apiGroup: rbac.authorization.k8s.io